# Generated by Django 3.2.7 on 2021-10-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercicios', '0002_exercicio_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='deleted',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='tipoExercisio',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
