# Generated by Django 3.2.7 on 2021-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercicios', '0003_auto_20211011_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='tipoExercisio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
