# Generated by Django 3.2.7 on 2021-10-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Exercicios', '0004_alter_exercicio_tipoexercisio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='tipoExercisio',
            new_name='tipoExercicio',
        ),
    ]
