# Generated by Django 3.2.7 on 2021-09-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTreino', models.CharField(max_length=255, unique=True)),
                ('tempoMinDuracao', models.PositiveIntegerField(null=True)),
                ('tempoMaxDuracao', models.PositiveIntegerField(null=True)),
                ('numeroSeries', models.PositiveIntegerField()),
                ('tipoTreino', models.PositiveIntegerField()),
            ],
        ),
    ]
