# Generated by Django 3.2.7 on 2021-09-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treinos', '0002_treino_usuarioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
