# Generated by Django 3.2.7 on 2021-10-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treinos', '0003_alter_treino_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='nomeTreino',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='treino',
            name='tempoMaxDuracao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='tempoMinDuracao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
