# Generated by Django 3.2.7 on 2021-10-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Treinos', '0004_auto_20211006_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='tempoMaxDuracao',
        ),
    ]
