# Generated by Django 3.2.7 on 2021-10-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Treinos', '0005_remove_treino_tempomaxduracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='deleted',
        ),
    ]
