# Generated by Django 3.2.7 on 2021-10-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Treinos', '0006_remove_treino_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='tipoTreino',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
